[nodejs]
symbol = "[⬢](bold green) "

[git_branch]
symbol = ' '

[git_metrics]
disabled = false

[git_status]
style = 'bg:black fg:bold green'

[cmake]
symbol = 'cmake '

[terraform]
symbol = ' '

[battery]
discharging_symbol = "⚡️ "

[gcloud]
symbol = '󰊶 '
format = '[$symbol$active]($style) '

[aws]
symbol = '  '

[time]
disabled = false
time_format = '%T UTC'
utc_time_offset = '0'
